environment:
  matrix:
    - PYTHON: "C:\\Python36"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade wheel pytest flake8 tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -e py36"

